server:
  port: 8011
spring:
  application:
    name: service-provider-user

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka