server:
  port: 8011
spring:
  application:
    name: consumer-movie-feign

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka