server:
  port: 8988
spring:
  application: 
    name: springcloud-config
  cloud: 
    config: 
      server:
        git:
          uri: https://github.com/liuhuayun/springcloudconfig.git
          username: 568656253@qq.com
          password: ABc568656253
          search-paths: '{application}'  #配置仓库路径
          force-pull: true
          clone-on-start: true
          default-label: master
          
eureka:
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka # eureka集群情况下，需要配置多个url逗号分隔向每个注册中心注册
          
