spring:
  application:
    name: spring-boot-admin
  profiles: 
    active: secure
server: 
  port: 8788

# tag::configuration-eureka[]

eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---
spring:
  profiles: insecure

---
spring:
  profiles: secure
security: 
  user: 
    name: admin
    password: admin
    
eureka:
  instance:
    metadata-map:
      user.name: admin         #These two are needed so that the server
      user.password: admin #can access the protected client endpoints