spring:
  application:
    name: consumer-movie-ribbon-hystrix
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000