spring:
  application:
    version: 2.0.3.RELEASE
    formatted-version: v2.0.3.RELEASE
    name: eureka-server-cluster
  profiles:
    active: server1
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS