spring:
  application:
    version: 2.0.3.RELEASE
    formatted-version: v2.0.3.RELEASE
    name: eureka-server-cluster
  profiles:
    active: server1
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  app: 
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"