server:
  servlet:
    context-path: /
  port: 8762
spring:
  security:
    user:
      name: admin
      password: admin
eureka:
  environment: test
  datacenter: cloud
  instance:
    hostname: server2
  server:
    #设为false，关闭自我保护
    enable-self-preservation: false
    #清理无效节点的时间间隔清理无效节点的时间间隔（单位毫秒，默认是60*1000）
    #eviction-interval-timer-in-ms: 5000
  client:
    #是否向服务注册中心注册自己，单机时设置false，集群时设置true
    registerWithEureka: true
    #是否检索服务
    fetchRegistry: true
    #服务注册中心的配置内容，指定服务注册中心的位置，单机时设置false，集群时设置true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka,http://admin:admin@server3:8763/eureka
      
      