spring:
  application:
    name: consumer-movie-ribbon
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
# 解决第一次请求报超时异常的方案：
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000    
#1.使用配置的方式配置ribbon自定义负载均衡(优先级：配置文件>代码配置>默认配置)
#service-provider-user: 
#  ribbon: 
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon脱离eureka单独使用，ribbon不会获取euraka注册列表
#ribbon:
#  eureka:
#   enabled: false  #禁用euraka
#service-provider-user: #指定可用服务
#  ribbon:
#    listOfServers: localhost:7900 