server:
  port: 8989
spring:
  application:
    name: springcloud-config-client
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: springcloud-config
    
eureka:
  client:
    service-url: 
      defaultZone: http://admin:admin@localhost:8761/eureka # eureka集群情况下，需要配置多个url逗号分隔向每个注册中心注册