server:
  servlet: 
    context-path: /
  port: 8031
spring:
  application:
    name: eureka-hystrix-turbine
eureka: 
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine: 
  aggregator: 
    clusterConfig: default #turbine需要聚合的集群名称,多个使用","分割 通过 http://localhost:8031/turbine.stream?cluster=default 访问 
  appConfig: consumer-movie-ribbon-hystrix,consumer-movie-feign-hystrix #配置需要聚合的应用,表明监控哪些服务
  clusterNameExpression: new String("default") #获取集群名El表达式，这里表示获取元数据中的cluster数据，在node01、node02为配置对应信息
#turbine.instanceUrlSuffix.clusterConfigname: /ribbon/hystrix.stream #监控的集群节点首页是/ribbon 需要这么配置